Feature refine valve tools
opsnow-tools/valve-tools pull request #2
Opened 2019-08-01 01:09 UTC by pakisto

2019-08-01 02:25 UTC, gelius7 approved these changes
ok

2019-08-01 05:03 UTC, longlg88 requested changes

2019-08-01 05:03 UTC, longlg88 commented on README.md
> +chart/\<namespace>/\<chartname>.yaml 파일의 상단에는 매니페스트를 생성하기 위한 몇 가지 조건을 설정할 수 있습니다. 여기에서 차트의 버전, 차트 레포지토리, 인rm레스 생성 여부, PVC 사용 여부 등을 명시할 수 있습니다.
인그레스 생성 이라고 변경하셔야 할 것 같습니다.

2019-08-01 05:03 UTC, longlg88 commented on documents/heapster.md
> +## Values.yamlN
N은 빼는게 맞겠죠?

2019-08-01 05:03 UTC, longlg88 commented on documents/kube-state-metrics.md
> +## Values.yamlN
N은 빼는게 맞겠죠?

2019-08-01 06:42 UTC, pakisto commented on README.md
> +chart/\<namespace>/\<chartname>.yaml 파일의 상단에는 매니페스트를 생성하기 위한 몇 가지 조건을 설정할 수 있습니다. 여기에서 차트의 버전, 차트 레포지토리, 인rm레스 생성 여부, PVC 사용 여부 등을 명시할 수 있습니다.
nice review

2019-08-01 06:45 UTC, pakisto commented on README.md
> +chart/\<namespace>/\<chartname>.yaml 파일의 상단에는 매니페스트를 생성하기 위한 몇 가지 조건을 설정할 수 있습니다. 여기에서 차트의 버전, 차트 레포지토리, 인rm레스 생성 여부, PVC 사용 여부 등을 명시할 수 있습니다.
modified

2019-08-01 06:45 UTC, pakisto commented on documents/heapster.md
> +## Values.yamlN
modified

2019-08-01 06:46 UTC, pakisto commented on documents/kube-state-metrics.md
> +## Values.yamlN
modified. thanks

2019-08-14 08:32 UTC, longlg88 approved these changes

2019-08-14 08:32 UTC, merged