add nginx-ingress for nodeport
opsnow-tools/valve-tools pull request #5
Opened 2019-08-21 08:09 UTC by longlg88

nginx-ingress의 nodeport type을 지원하기 위해 다음을 변경했습니다.
- run.sh
- charts/kube-ingress/nginx-ingress-nodeport.yaml

2019-08-21 08:49 UTC, gelius7 commented on run.sh
> +    if [[ "${NAME}" == "nginx-ingress" ]]; then
* 를 위해 [[ ]] 를 사용했었는데 * 를 제외하니 다른 if 문과 동일하게 [] 하나짜리로 변경 바랍니다.

2019-08-21 08:50 UTC, gelius7 requested changes
코멘트 확인해주세요

2019-08-21 08:53 UTC, longlg88 commented
반영했습니다.

2019-08-21 09:50 UTC, gelius7 approved these changes

2019-08-21 09:50 UTC, gelius7 commented
룩스 구우우우웃 투 미

2019-08-22 09:12 UTC, pakisto approved these changes

2019-08-22 09:12 UTC, merged